iste610/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^$', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

polls/models.py
from __future__ import unicode_literals

from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'



class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text
    

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render, render_to_response 
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils.encoding import smart_str

from pymongo import MongoClient

from bson.objectid import ObjectId
import bson


#set mongo client to e c2 instance and the collection to tweets for this assingment
client = MongoClient('ec2-52-27-233-131.us-west-2.compute.amazonaws.com', 27017)
db = client.users
dbname = db._Database__name
collection = db.tweets
collname = collection.collection._Collection__name


#loading the index 
def index(request):
	context = None
	template = loader.get_template('polls/index.html')
	resultsStr = 'No results available.'
	username = ''
	next = ''
	tweetbody = ''
	totalsize = 0
		
	if request.method == 'POST':
		#sets variables based on the request post keys	
		if 'comments' in request.POST.keys():
			id = request.POST['id']
			collection.update({'_id':ObjectId(id)},{'$set':{"comment":request.POST['comments']}})
				
		if 'nextvalue' in request.POST.keys():
			next = int(request.POST['nextvalue'])
		else:
			next = 0
		
		#when username and tweetbody are passed ie search we run mongo query and fetch results
		if 'username' in request.POST.keys() and 'tweetbody' in request.POST.keys():
			username = request.POST['username']
			tweetbody = request.POST['tweetbody']
	
			username = username.strip()
			tweetbody = tweetbody.strip()
			
			limitval = 15
			if username == '' and tweetbody == '':
				query = {}
				
			elif username == '':
				query = {'text':{"$regex":'.*'+str(tweetbody)+'.*'}}
			
			elif tweetbody == '' :
				query = {'fromUser':{"$regex":'.*'+str(username)+'.*'}}
			else:
				query = {'text':{"$regex":'.*'+str(tweetbody)+'.*'},'fromUser':{"$regex":'.*'+str(username)+'.*'}}
			
			results = collection.find(query)
			totalsize = results.explain()['n']
			totalpages = totalsize//15 + 1
			
			#used skip and limit to limit searches and have pages of results
			results.skip(next*limitval).limit( limitval )
			resultsStr = '<table>'
			
			#obtain the results and build an html tables to inject into the display tweet when user clicks "View Tweet" div in index.html file
			for result in results:
				if 'text'  in result and 'fromUser' in result:
					
				
					text     = result['text']
					text 	 = text.replace("'","\ ")
					text 	 = text.replace('"','\ ')
					resultid = str(result['_id'])
					fromUser = str(result['fromUser'])
					injectedHTML  = '<form id= &quot;comments&quot; name= &quot;comments&quot; action= &quot;/&quot; method=&quot;post&quot;p>'
					injectedHTML += '<table>'
					injectedHTML += ' <tr><td>Tweet ID:</td><td>'+str(result['_id'])+'</td></tr>'
					injectedHTML += '<tr><td>User Name:</td><td>'+result['fromUser']+'</td></tr>'
					injectedHTML += '<tr><td>Tweet Text:</td><td>'+text+'</td></tr>'
					injectedHTML += '<tr><td>Latitude:</td><td>'+str(result['latitude'])+'</td></tr>'
					injectedHTML += '<tr><td>Longitude:</td><td>'+str(result['longitude'])+'</td></tr>'
					injectedHTML += '<tr><td>Tweeted At:</td><td>'+result['createdAt']+'</td></tr>'
				
					#if there is comment then display comment else display nothing
					if 'comment' in result.keys():
						comments = result['comment']
						comments = comments.replace("'","\ ")
						comments = comments.replace('"','\ ')
					else:
						comments = ''
				
					injectedHTML += '<tr><td>Comments: </td><td>'+comments+'</td></tr>'
				
					#button for displaying comment
					injectedHTML += '<tr><td><button name=&quot;addcomment&quot; type=&quot;submit&quot;>Add Comment</button></td><td><input type=&quot;text&quot; name=&quot;comments&quot; value=&quot; &quot;></td></tr>'
					injectedHTML += '</table>'
					injectedHTML += '<button type = &quot;button&quot; onclick=linktogooglemaps(&quot;'+str(result['latitude'])+','+ str(result['longitude'])+'&quot;); class=&quot;buttons&quot;>Google Map Location</button>'
				
					#hidden post values 
					injectedHTML += '<input type=&quot;hidden&quot; name=&quot;id&quot; value=&quot;'+str(result['_id'])+'&quot;/>'
					injectedHTML += '<input type=&quot;hidden&quot; name=&quot;username&quot; value=&quot;'+username+'&quot;/>'
					injectedHTML += '<input type=&quot;hidden&quot; name=&quot;tweetbody&quot; value=&quot;'+tweetbody+'&quot; />'
					injectedHTML += '<input type=&quot;hidden&quot; name=&quot;nextvalue&quot; value=&quot;'+str(next)+'&quot; />'
								
					#view tweet button with injected html to propegate to tweetdisplay div onclock
					button 		  = '''<button type = "" onclick="getElementById('tweetdisplay').innerHTML = ' ''' +injectedHTML+''' ' ;show();">View Tweet</button> '''
				
					#String that is displayed in result div, view tweet button, fromUser and created AT
					resultsStr   += "<tr><td>" + button+ "</td><td>" + str(result['fromUser']) + "</td><td>" + str(result['createdAt']) + "</td></tr>"
				
				
				
			resultsStr += '</table>'
			#limited the number of search to speed up searches of large query, next and previous go through pages of results
			if next != 0:
				resultsStr += '<form id="results" name="resultsform" action="/" method="post"><button name="nextvalue" type="submit" value="'+str(next-1)+'">Previous</button>'
			if next+1 != totalpages:
				resultsStr += '<form id="results" name="resultsform" action="/" method="post"><button name="nextvalue" type="submit" value="'+str(next+1)+'">Next</button>'
			
			
			
			#if totalsize of search was 0 ie no result found show now result otherwise show the numer of page out of all pages
			if totalsize != 0:
				resultsStr += '<span>&nbsp;&nbsp;&nbsp;&nbsp;' +str(next+1) + ' out of '+ str(totalpages)+ '</span>'
			else:
				resultsStr +=  'No results available'
			resultsStr += '<input type="hidden" name="username" value="'+username+'"/>'
			resultsStr += '<input type="hidden" name="tweetbody" value="'+tweetbody+'" />'
			#resultsStr += '</form>'
			
			
			context = RequestContext(request, {'resultsStr': resultsStr,})
	
	#injecting the searchbox, prepopulated with text if availble, this is used so that username and tweetbody are persisted through all of our post request unless set
	searchbox = '''<label for="username">Search by User: </label>
					<input type="text" id="username" name="username" autocomplete="on" value ="''' 
	searchbox += str(username)			
	searchbox += '''" size="25"/><br/><br/>
					<!--span>Search by Time/Date of Tweet:&nbsp;&nbsp;&nbsp;</span>
					<label for="starttime">Start: </label>
					<input type="text" id="starttime" name="starttime" size="18"/>
					<label for="stoptime">&nbsp;&nbsp;&nbsp;Stop: </label>
					<input type="text" id="stoptime" name="stoptime" size="18"/><br/>
					</br-->
					<label for="tweetbody">Search by Tweet Content:</label>
					<input type="text" id="tweetbody" name="tweetbody" value = "'''
	searchbox += str(tweetbody)				
	searchbox +=	'''" autocomplete="on" size="65"/><br/><br/>
					<input type='hidden' name='csrfmiddlewaretoken' value='{{csrf_token}}'>
				</div><!-- end formfeild   -->
				<div id="buttonfeild">
					<input type="hidden" name="csrfmiddlewaretoken" value="pHK2CZzBB323BM2Nq7DE2sxnQoBG1jPl" disabled="">
					<input type="submit" value="Search" class="buttons"/>
					<button type = "button" class="buttons" onclick="reload();">Reset</button>'''
					#<button type = "button" class="buttons" onclick="resetTest()">Reset</button>'''
	
	#passing python object parameters to the template file(index)
	params = {"resultsStr":resultsStr, "client":str(client.address),'searchbox':searchbox,'totalsize':totalsize,'dbname':dbname,'collname':collname}
	
	#if resultsStr == '':
	return render_to_response("polls/index.html",params, context_instance=RequestContext(request))
	#else:
	#	return render_to_response("polls/index.html",params, context_instance=RequestContext(request))

polls/templates/polls/index.html
{% load staticfiles %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<title>ISTE610 Group Project :: Twitter Search</title>
	<style type="text/css">

		body {background-color:#7cb2d4;}
		#bodywrapper {width:1000px;
		margin:0px auto;}

		.FramedDisplayElement {border:2px inset;
		padding:20px;
		margin:5%;
		background-color:#a2bbcb;}

		#leftside {width:69%;
		float:left;
		display:inline-block;
		clear:left;}

		#RightSide {width:29%;
		float:right;
		text-align:center;
		margin-top:10px;
		display:inline-block;
		vertical-align:top;}

		.PageText,h1,h3 {text-align:center;
		color:#333333;}

		#introduction {width:60%;
		margin:auto;
		text-align:left;}

		#sysdisplay {height:100px; overflow:hidden;}
		#searchform {height:200px;}
		#resultsdisplay {min-height:300px; overflow:auto;}
		#tweetdisplay {display:none;}

		img {border:1px solid #000000;}

		td	{padding:8px 15px 8px 15px; border-bottom:1px outset;}

		#tweetdisplay table {width:100%}
		#tweetdisplay table tr td {min-width:100px;}
		#map {
        
        height: 400px;
      	visibility:hidden;
      	}
      	
					
	</style>
	
	<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?sensor=false">
</script>

	
	<script type="text/javascript">	
	var map;
		
	$(document).ready(function(){
    
     document.getElementById('resultsdisplay').scrollIntoView();
	});	
	//on view tweet display the tweetdisplay div
	function show() { 
        document.getElementById('tweetdisplay').style.display='block'; 
        document.getElementById('tweetdisplay').scrollIntoView();
        document.getElementById('map').style.visibility='hidden'; 
        return false;
    } 
   
    function msg(msg) {
    	document.getElementById("sysdisplay").innerHTML=msg;
    }
    //reloading the webpage
    function reload() {
    	window.location='http://dantheran7.ddns.net/';
    }

	//google map function passed on the coordiantes in the tweetdisplay div
	function linktogooglemaps(coor) 
	{
	coorArr = coor.split(",");
	latNum = coorArr[0] 
	longNum = coorArr[1]
	document.getElementById('map').style.visibility='visible';
	var mapCanvas = document.getElementById('map');
	var mapOptions = {
      		center: new google.maps.LatLng(latNum,longNum),
      		zoom: 15,
      		mapTypeId: google.maps.MapTypeId.ROADMAP
    	}
    var map = new google.maps.Map(mapCanvas, mapOptions); 

	var marker = new google.maps.Marker({
        position: new google.maps.LatLng(latNum,longNum),
        map: map,
        title:"This is the place."
    });  
 
    var contentString = 'Hello <strong>World</strong>!';
    var infowindow = new google.maps.InfoWindow({
        content: contentString
    });
 
    google.maps.event.addListener(marker, 'click', function() {
      infowindow.open(map,marker);
    });
    }
	
	
		
	function initialize() {
    	var mapCanvas = document.getElementById('map');
    	var mapOptions = {
      		center: new google.maps.LatLng(44.5403, -78.5463),
      		zoom: 8,
      		mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas, mapOptions);
  } 
  google.maps.event.addDomListener(window, 'load', initialize); 
	</script>
</head>

<body>
	<!-- The body wrapper prevents the site from stretching to extremes  -->
	<div id="bodywrapper">
	<!--  Left side contains the fuctional components of the site, the server feedback, search form and search results -->
	<div id="leftside">
		
		<h1  onclick="msg('hey');">ISTE610 Group Project :: Twitter Search</h1>
		<p id="introduction" class="PageText">For Searching the Twitter Database:<br/>
			The system will start automatically, you can check the connection status in the window below. Once the connection is successful you will be able to search the database and interact with the results.</p>
		
		<!-- The sysdisplay contains the readou from the server detailing the connection and connection status  -->
		<div id="sysdisplay" class="FramedDisplayElement">
		{% if resultsStr %}		
			{% if client %}
    		<p>System Ready.<br>Connected to server {{client}}.<br/>Database {{dbname}}, collection {{collname}}.<br/>{{ totalsize }} results obtained.</p>
			{% else %}
    		<p>FAILURE. No connection.</p>
			{% endif %}
		{% else %}			
    		<p>System Ready.</p>
			
		{% endif %}


		
		</div><!-- end sysdisplay   -->
		
		<!-- Search form contains the form for submitting queries against the database  -->
		<div id="searchform" class="FramedDisplayElement">
			<h3>Please fill out the form below to search the Twitter database</h3>
			<form id="queryform" name="queryform" action="{% url 'polls:index'%}" method="post">
				{% csrf_token %}
				<div id="formfeild">
				{% if searchbox %}
			
			
				{% autoescape off %}
				{{ searchbox }}
				{% endautoescape %}
				{% csrf_token %}
			
				{% endif %}	
				</div><!--  end buttonfeild  -->
			</form>
		</div><!-- end searchform  -->
		
		<!-- Resultsdisplay contains the result of the queries as a list for which further entries can be selected  -->
		
		<div id="resultsdisplay" class="FramedDisplayElement">
			{% csrf_token %}
			{% if resultsStr %}
			
			{% autoescape off %}
			{{ resultsStr }}
			{% endautoescape %}
			{% csrf_token %}
			</form>
		{% else %}
		<div id="resultsdisplay" class="FramedDisplayElement" style="display:none;">
    		<p>No results are available.</p>
		{% endif %}
			<!-- {% if userNameList %}
			<table>
			{% for result in userNameList %}
    		<tr><td>
    		{{ result }}
    		</tr></td>
    		{% endfor %}
    		</table>
			{% else %}
    		<p>No results are available.</p>
			{% endif %}
		-->
		
		</div><!-- end resultsdisplay  -->
		
		
		
		
		{% if resultsStr %}
		<form id= "comments" name= "comments" action= "/" method="post">
		{% csrf_token %}
		
		<div id="tweetdisplay" class="FramedDisplayElement">
		
		</div>
		</form> 
		{% endif %}	
		
		
	
	<div class="FramedDisplayElement" id="map"></div>	
		
	</div><!--  end left side  -->
	
	<!-- Right side display - for team photos and project text  -->
	<div id="RightSide">
		<br/>
		<h3>About Our Project</h3>
		<hr/>
		<h3>Our Team Members</h3>
		<p class="PageText">
			<img src="{% static 'polls/Dan.jpg' %}" width="150px"/><br/>
			<span>Daniel Mooney</span>
			<br/>
			<br/>
			<img src="{% static 'polls/eduardo.jpg' %}" width="150px"/><br/>
			<span>Eduardo Coelho Lima</span>
			<br/>
			<br/>
			<img src="{% static 'polls/John.jpg' %}" width="150px"/><br/>
			<span>John Dettmer</span>
			<br/>
			<br/>
		</p>
		<hr/>
		<p class="PageText" style="text-align:left; font-size:80%;">
			<span style="font-weight:bold;">About this site and our project:</span></br></br>
 
			Since the functionality of this project is relatively simple and direct, we’ve taken an approach of having the sight function as a single page, rather than bouncing the user between pages. As content (search results) are generated additional areas of the page open up to display the information. </br></br>

			The display page is built with HTML with both local and inline CSS styling. 4 primary divs make up the main display area showing, a read out of the current system, the form for searching the dataset, the results of the search, and the selected individual tweet. Some JavaScript was utilized in managing the divs and reset fuctionality, and also in the display of the google map included as an option when viewing a tweet. </br></br>

			The back end of the site functions using Python with support of a Django framework, which is one of the most popular frameworks available for the web. The PyMongo library was used to connect to the MongoDB which was hosted on Amazons EC2 cloud. </br></br>

			Testing and development and hosting of the website was facilitated though installation of the required components on a RaspberryPi which performed without issue. After starting development we also cloned the project on GitHub for future reference and functionality.</br></br>

			Communication for the project was done through Google Hangouts and e-mail, while in chat we would functionally pass control of elements of the site between us to allow for updates.
 
		</p>
	</div><!-- End of the Right Side  -->
	
	</div><!-- End of the body wrapper  -->
</body>
</html>